/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      divideColor: {
        'primary-light': '#2A9DdF',
        'primary-dark': '#4CAF50',
        'secondary-light': '#F4A261',
        'secondary-dark': '#E76F51',
        'neutral-light': '#caccd1',
        'neutral-dark': '#52565e',
      },
      backgroundColor: {
        'primary-light': '#f5f8fa',
        'primary-dark': '#1e1e1e',
        'secondary-light': '#aab8c2',
        'secondary-dark': '#242424',
        'neutral-dark': '#52565e',
        'neutral-light': '#caccd1',
        'success-light': '#8BC34A',
        'success-dark': '#4CAF50',
        'warning-light': '#FFEB3B',
        'warning-dark': '#FFC107',
        'danger-light': '#EF5350',
        'danger-dark': '#D32F2F',

        'color-light': '#2A9D8F',
        'color-dark': '#264653',
        'color2-light': '#F4A261',
        'color2-dark': '#E76F51',

        // dark green
        'color3-light': '#84bd00',
        'color3-dark': '#009f4d',

        'teal-light': '#2DD4BF',
        'teal-dark': '#14B8A6',
      },
      textColor: {
        'primary-light': '#444444',
        'primary-dark': '#eeeeee',
        'secondary-light': '#0021a5',
        'secondary-dark': '#E76F51',
        'neutral-light': '#888888',
        'neutral-dark': '#caccd1',
        'neutral-charcoal': '#333333',
        'success-light': '#8BC34A',
        'success-dark': '#4CAF50',
        'warning-light': '#FFEB3B',
        'warning-dark': '#FFC107',
        'danger-light': '#EF5350',
        'danger-dark': '#D32F2F',

        'color-light': '#2A9D8F',
        'color-dark': '#264653',
        'color2-light': '#F4A261',
        'color2-dark': '#E76F51',
        'teal-light': '#2DD4BF',
        'teal-dark': '#14B8A6',
      },
      borderColor: {
        'primary-light': '#2A9D8F',
        'primary-dark': '#264653',
        'secondary-light': '#F4A261',
        'secondary-dark': '#E76F51',
        'error-light': '#EF5350',
        'error-dark': '#D32F2F',
        'success-light': '#8BC34A',
        'success-dark': '#4CAF50',
      },
      backgroundOpacity: {
        10: '0.1',
        90: '0.9',
      },
      ringColor: {
        'primary-light': '#2A9D8F',
        'primary-dark': '#264653',
        'secondary-light': '#F4A261',
        'secondary-dark': '#E76F51',
      },
      placeholderColor: {
        'primary-light': '#444444',
        'primary-dark': '#eeeeee',
        'secondary-light': '#0021a5',
        'secondary-dark': '#E76F51',
        'neutral-light': '#E0E0E0',
        'neutral-dark': '#888888',
        'neutral-charcoal': '#333333',
        'success-light': '#8BC34A',
        'success-dark': '#4CAF50',
        'warning-light': '#FFEB3B',
        'warning-dark': '#FFC107',
        'danger-light': '#EF5350',
        'danger-dark': '#D32F2F',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
