import "../globals.css";
import ThemeProviders from "../../context/theme/provider";

import { Inter } from "next/font/google";
import Navbar from "@/components/app_shell/navbar/Navbar";
import Sidebar from "../../components/app_shell/sidebar/Sidebar";
import { getServerSession } from "next-auth";
import { authOptions } from "../../app/api/auth/[...nextauth]/route";

import { redirect } from "next/navigation";
import MainPageLayout from "@/components/ui/containters/MainPageLayout";
import SimpleNotification from "@/components/partials/notifications/SimpleNotification";
const inter = Inter({ subsets: ["latin"] });
import { sendMessageToAllClients } from "../../lib/utils/ws";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/login");
  }

  return (
    <html
      className="h-full bg-primary-light dark:bg-primary-dark overflow-hidden"
      suppressHydrationWarning
      lang="en"
    >
      <body
        aria-live="assertive"
        className="flex h-[100%] bg-primary-light dark:bg-primary-dark"
      >
        <ThemeProviders>
          <Sidebar />

          <div
            className="flex flex-col overflow-y-scroll w-[100%]"
            // className="pointer-events-none fixed inset-0 flex items-end px-4 py-6 sm:items-start sm:p-6"
          >
            <Navbar />
            <MainPageLayout>{children}</MainPageLayout>
          </div>
        </ThemeProviders>
      </body>
    </html>
  );
}
