import PublicNavbar from '@/components/app_shell/navbar/PublicNavbar';
import '../globals.css';
import ThemeProviders from '../../context/theme/provider';
import Head from 'next/head';

// export const metadata = {
//   title: 'WLS APP',
//   description: 'Generated by create next app',
//   link: {
//     rel: 'manifest',
//     href: '/manifest.json',
//   },
// };

export default async function RootLayout({ children }) {
  return (
    <html
      className="h-full bg-primary-light dark:bg-primary-dark"
      suppressHydrationWarning
      lang="en"
    >
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className="">
        <ThemeProviders>
          <PublicNavbar />
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
