import '../globals.css';
import ThemeProviders from '../../context/theme/provider';

import PublicNavbar from '@/components/app_shell/navbar/PublicNavbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  return (
    <html
      className="h-full bg-primary-light dark:bg-primary-dark"
      suppressHydrationWarning
      lang="en"
    >
      <body className="">
        <ThemeProviders>
          <PublicNavbar />
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
